### ISSUE TITLE
When printer not connected, tone preview in Events screen not working

### ISSUE THREAD

**Issue by andritolion** [stealthmonkey99/OctoPrint-PWMBuzzer#10]
When a 3D printer isn't connected to the Raspberry Pi, the Try it button does not work. The tone should preferably play both when a 3D printer is or isn't connected, or the UI should communicate that preview can only be done when a printer is connected.

**Comment by stealthmonkey99** [comment]
Also the "Send Gcode to Printer" button on the Composer tab won't work without a connected printer, might be good to disable it when disconnected (or at least handle the error to indicate why it won't work).
