### ISSUE TITLE
M300 suppression setting does not persist

### ISSUE THREAD

**Issue by wlbillmartin** [stealthmonkey99/OctoPrint-PWMBuzzer#18]
Two things:
I keep selecting Suppress M300 command passthrough but it doesn't save this setting. When I select it, I can test sounds and composer and life is great, but when I select "Save" and then go back to OctoPrint and Upload a file, I get the tone as well as my printer beeping.

Also, I use the OctoPrint-M117SpeechSynthesis plugin (https://github.com/jneilliii/OctoPrint-M117SpeechSynthesis) as well and like when the computer says the M117 items I've put in the G-Code. But it plays on my computer through the browser. It would be really kewl if these items would play on the speaker I'm using.

Other than that, this is a really kewl plugin. I just wish I could silence my printer's beeper when things play through your plugin.

THANKS!!!

**Comment by stealthmonkey99** [comment]
Thanks for the heads up on the suppression issue, I'll take a look this weekend and see if I can reproduce the problem with my setup.

I love the idea for the M117 speech synth, but that would be a lot more complicated... maybe a future hackathon project for the other plug-in's owner @jneilliii and I to consider 😅.  I suspect wiring that up to the standard audio jack would be a lot better sounding (and hopefully simpler?) than trying to modulate a buzzer, though 😎

**Comment by jneilliii** [comment]
Interesting idea. Switching speechsynthesis to server side would require figuring out the text to speech bits. What I'm doing now in the plugin is all browser side, where it's built-in. 

As for the issue at hand, I think doing a quick look that https://github.com/stealthmonkey99/OctoPrint-PWMBuzzer/blob/719ae4a7bb806cad3f532701595948d59f679f56/octoprint_pwmbuzzer/__init__.py#L190 should be
```
self._suppress_m300 = bool(data["hw"].get("hw_suppress_m300"))
```

**Comment by stealthmonkey99** [comment]
ah bummer, actually that line looks okay but for some reason I dropped the setting when the others get saved here: https://github.com/stealthmonkey99/OctoPrint-PWMBuzzer/commit/3e210a5c48b36d3082dbadd8e61f3179c3b43e73#diff-492f80fc0155cb4f5e01eaf596334e19f63d04b2dd9507eff12d9d2f6ca54ee2L190

Fix is on the way!

**Comment by stealthmonkey99** [comment]
@wlbillmartin you can add the plugin using this URL to fix it:

    https://github.com/stealthmonkey99/OctoPrint-PWMBuzzer/archive/fix-m300-suppression.zip

and I'll include this fix in an upcoming release soon :)

**Comment by wlbillmartin** [comment]
Works perfectly now! THANK YOU!!!

**Comment by jneilliii** [comment]
@wlbillmartin I actually just remembered that 28 days ago I release version 1.0.0 of M117SpeechSynthesis that outputs the audio on the pi's connected speaker, just have to have one connected. I don't think you're going to get speech out of a pwm buzzer though.

**Comment by wlbillmartin** [comment]
I'm using this one from Amazon (it was on the recommended list) and it sounds rather nice, even on the "tunes" such at Twinkle and Mario:
https://www.amazon.com/dp/B097T7N6DC
It also plugs nicely into GPIO 16 & Ground and it's a real speaker, rather than a buzzer.

**Comment by jneilliii** [comment]
interesting, that's cool. I'm not sure what you would have to do on the linux side to set that as a default audio device that would be picked up by pyttsx3 (module I'm using to send the audio when the use pi speaker option is enabled). All my development testing was done directly on my laptop so it just worked.

**Comment by jneilliii** [comment]
little more reading and probably not possible. seems this might work good for the tones because it's being driven by PWM signals, not actually acting as an audio device.

**Comment by wlbillmartin** [comment]
Yeah... I agree. But it's a pretty good sounding buzzer. I've tried to upload some midi files I made in Microsoft Music Producer (yeah, from the Windows 98 Microsoft Plus! pack and hacked to work on Win 7, 10, etc.), but they're not being accepted.
As was mentioned that midi stuff was experimental, I'll wait and see what happens.
I'm not going to post an issue on this unless it's requested.
